version: "3"
services:
  # bootnode:
  #   hostname: bootnode
  #   build:
  #     context: ./bootnode
  #   environment:
  #     NODEKEYHEX: ${NODEKEYHEX}

  migrate-1:
    build:
      context: ./
      dockerfile: migration/Dockerfile
    environment:
      SIGNER1PW: ${SIGNER1_PW}
      SIGNER1KEY: ${SIGNER1_KEY}
      SIGNER1ADD: ${SIGNER1_ADD}
      SIGNER2PW: ${SIGNER2_PW}
      SIGNER2KEY: ${SIGNER2_KEY}
      SIGNER2ADD: ${SIGNER2_ADD}
      SIGNER3PW: ${SIGNER3_PW}
      SIGNER3KEY: ${SIGNER3_KEY}
      SIGNER3ADD: ${SIGNER3_ADD}
      SIGNER4PW: ${SIGNER4_PW}
      SIGNER4KEY: ${SIGNER4_KEY}
      SIGNER4ADD: ${SIGNER4_ADD}
      ENODEPUB_1: ${ENODEPUB_1}
      ENODEPUB_2: ${ENODEPUB_2}
      NETWORK_CHAIN_ID: ${NETWORK_CHAIN_ID}
    volumes:
      - eth-data-1:/app/datadir
      - ./config/migrateSigners.js:/app/migrateSigners.js
  signer-1:
    hostname: signer-1
    build:
      context: ./
      dockerfile: signer/Dockerfile
    environment:
      SIGNERPW: ${SIGNER3_PW}
      SIGNERKEY: ${SIGNER3_KEY}
      SIGNERADD: ${SIGNER3_ADD}
      SIGNER2ADD: ${SIGNER4_ADD}
      ENODEPUB_1: ${ENODEPUB_3}
      ENODEPUB_2: ${ENODEPUB_4}
      SIGNER1DOMAIN: signer-1
      SIGNER2DOMAIN: signer-2
      NETWORK_CHAIN_ID: ${NETWORK_CHAIN_ID}
    volumes:
      - eth-data-1:/app/datadir
    # depends_on:
    #   - migrate-1
  signer-2:
    hostname: signer-2
    build:
      context: ./
      dockerfile: signer/Dockerfile
    environment:
      SIGNERPW: ${SIGNER4_PW}
      SIGNERKEY: ${SIGNER4_KEY}
      SIGNERADD: ${SIGNER4_ADD}
      SIGNER2ADD: ${SIGNER3_ADD}
      ENODEPUB_1: ${ENODEPUB_3}
      ENODEPUB_2: ${ENODEPUB_4}
      SIGNER1DOMAIN: signer-1
      SIGNER2DOMAIN: signer-2
      NETWORK_CHAIN_ID: ${NETWORK_CHAIN_ID}
    volumes:
      - eth-data-2:/app/datadir
    depends_on:
      - signer-1
  client-1:
    hostname: client-1
    build:
      context: ./
      dockerfile: client/Dockerfile
    environment:
      ENODEPUB_1: ${ENODEPUB_1}
      ENODEPUB_2: ${ENODEPUB_2}
      NETWORK_CHAIN_ID: ${NETWORK_CHAIN_ID}
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - eth-data-3:/app/datadir
    depends_on:
      - signer-1
      - signer-2

  client-2:
    hostname: client-2
    build:
      context: ./
      dockerfile: client/Dockerfile
    environment:
      ENODEPUB_1: ${ENODEPUB_1}
      ENODEPUB_2: ${ENODEPUB_2}
      NETWORK_CHAIN_ID: ${NETWORK_CHAIN_ID}
    ports:
      - "8547:8545"
      - "8548:8546"
    volumes:
      - eth-data-4:/app/datadir
    depends_on:
      - signer-1

  explorer:
    build:
      context: ./explorer
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      WEB3PROVIDER: "ws://localhost:8546"
    depends_on:
      - client-1

  ethereum-lite-explorer:
    depends_on:
      - client-1
    image: alethio/ethereum-lite-explorer
    environment:
      - APP_NODE_URL=ws://localhost:8546
    ports:
      - "8081:80"

  blockscout:
    hostname: blockscout
    depends_on:
      - client-1
      - db
    # image: blockscout
    build:
      context: ./blockscout
      args:
        COIN: tETH
    restart: on-failure
    env_file:
      - ./blockscout/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      BLOCK_TRANSFORMER: clique
      ETHEREUM_JSONRPC_HTTP_URL: http://client-1:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://client-1:8546
      DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
      ECTO_USE_SSL: "false"
      SUBNETWORK: "Dev"
      SECRET_KEY_BASE: VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No
      DISABLE_EXCHANGE_RATES: "true"
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: "true"
      LINK_TO_OTHER_EXPLORERS: "false"
      SUPPORTED_CHAINS: "[]"
      APPS_MENU: 0
      HIDE_FOOTER: 1
      SHOW_DASHBOARD_GRAPH: 0
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 1
      INDEXER_MEMORY_LIMIT: 2
      SHOW_ADDRESS_MARKETCAP_PERCENTAGE: 0
      DISABLE_READ_API: 0
      DISABLE_WRITE_API: 0
    ports:
      - 8082:4000
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    # ports:
    #   - 7432:5432
    
    volumes:
      - db-data:/var/lib/postgresql/data

  dashboard:
    hostname: dashboard
    depends_on:
      - client-1
    build:
      context: ./ethstats-dashboard
    environment:
      WS_SECRET: ${WS_SECRET_ETHSTATS}
    ports:
     - 8083:3000

  dashboard-stats:
    depends_on:
      - dashboard
    build:
      context: ./ethstats-reporter
    environment:
      WS_SECRET: ${WS_SECRET_ETHSTATS}
    volumes:
      - ./ethstats-reporter/app.json:/opt/ethstats/app.json:ro

volumes:
  eth-data-1:
  eth-data-2:
  eth-data-3:
  eth-data-4:
  db-data:
